# -*- coding: utf-8 -*-
"""Guessing_game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3uBLdQBzsoI6aIzit89SHPGS_GmTMfj
"""

SECRET = 42                      # constant — capitalized by convention (Day 2)
tries = 0

while True:
    guess = int(input("Guess a number between 1 and 100: "))

    # Guard: invalid input doesn't count
    if guess < 1 or guess > 100:
        print("Invalid guess")
        continue

    tries += 1                   # only valid guesses count

    if guess == SECRET:
        word = "try" if tries == 1 else "tries"
        print("🎉 You got it! It took you", tries, word)
        break
    elif guess > SECRET:
        print("📈 Too high! Try lower.")
    else:
        print("📉 Too low! Try higher.")