# -*- coding: utf-8 -*-
"""Tip_Calculator.ipynb

Automatically generated by Colab.

"""
Smart Tip Calculator v1.1
--------------------------
A command-line tool that calculates tips based on service rating,
splits the bill across multiple people, and supports custom tip override.

Built as Project 1 of my 30-day Python journey.

Features:
- Service-rating-based tip percentages (1-5 scale)
- Input validation (rating range, splitter count)
- Custom tip percentage override
- Clean receipt-style output

Usage:
    python day7_tip_calculator.py
"""

bill_amount = float(input(" enter the bill amount "))
rating = int(input(" enter the hotel rating from 1-5 "))
splitting_people = int(input(" enter the number of people to split the bill "))
if rating < 1 or rating > 5:
    print("⚠️ Invalid rating. Please enter 1-5.")
elif splitting_people <= 0:
        print("⚠️ Number of people must be at least 1.")
else :
    if rating == 1:
        tip_percentage = 0
        label = "Terrible"
    elif rating == 2:
        tip_percentage = 5
        label = "Poor"
    elif rating == 3:
        tip_percentage = 10
        label = "Average"
    elif rating == 4:
        tip_percentage = 15
        label = "Good"
    else :
        tip_percentage = 20
        label = "Excellent"

    override = input("want to override the tip percentage yes/no ")
    if override == "yes":
         tip_percentage = float(input(" enter the tip percentage "))
         label = "Custom"



    tip_amount = bill_amount * (tip_percentage/100)
    total_amount = bill_amount + tip_amount
    per_person_amount = total_amount / splitting_people
    print("========== RECEIPT ========== ")
    print("Bill amount : ",round(bill_amount,2))
    print("Service Rating: ",rating," out of 5","(",label,")")
    print("Tip Percentage : ", tip_percentage, "%")
    print("Tip amount : ", round(tip_amount,2))
    print("Total bill :", round(total_amount,2))
    print("Split Between :", splitting_people ,"people")
    print("per person amount :", round(per_person_amount,2))
    print("===============================")

